FROM apache/hadoop:3

RUN sudo yum install -y python3 python3-pip

RUN pip3 install mrjob --user
RUN pip3 install cassandra-driver --user
RUN pip3 install kafka-python --user
RUN pip3 install hdfs --user
